[project]
name = "routevolt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "faker>=40.36.0",
    "fastapi>=0.141.1",
    "geopy>=2.5.0",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.1",
    "xgboost>=3.4.1",
]
